AABB-based frustum culling of `RenderChunk2d`.
StarArawn/bevy_ecs_tilemap pull request #288
Opened 2022-09-25 15:56 UTC by bzm3r

Fixes: https://github.com/StarArawn/bevy_ecs_tilemap/issues/282

2022-09-25 15:59 UTC, bzm3r commented on src/helpers/transform.rs
> +pub fn apply_transform_to_aabb(transform: Transform, aabb: Aabb) -> Aabb {
Not sure if this is right.

2022-09-26 01:37 UTC, bzm3r commented on src/helpers/transform.rs
> +pub fn apply_transform_to_aabb(transform: Transform, aabb: Aabb) -> Aabb {
This is unnecessary, it turns out.

2022-09-26 13:34 UTC, StarArawn requested changes
Overall things are looking really good here!

It looks like frustum culling is broken for diamond isometric maps. From what I can tell it's caused by an incorrect AABB size. I would also like for us to have a setting to turn on/off the frustum culling as some people might want to disable that feature. Maybe as a component on the tilemap entity?

2022-09-26 18:32 UTC, Affinator commented
> 

What about a setting in the RenderSettings? This will not be decided per tilemap, but globally...

2022-09-26 21:11 UTC, bzm3r commented
@Affinator I think having the flexibility of making it a tilemap specific setting is good? I have set the default to be "Frustum culling on", so that it 99% of the time you don't have to think about it.

2022-09-28 02:21 UTC, StarArawn approved these changes

2022-09-28 02:40 UTC, merged