Revising neighbor helpers for ergonomicness. Removing requirement of supplying a TileStorage element to get neighbour positions.
StarArawn/bevy_ecs_tilemap pull request #328
Opened 2022-10-27 00:13 UTC by bzm3r

2022-10-28 14:39 UTC, StarArawn requested changes
Conflicts need to be fixed, but this is looking good! 👍

2022-11-04 15:14 UTC, StarArawn approved these changes

2022-11-11 22:08 UTC, nerdachse commented
Can this be merged before the next release for bevy 0.9 please?

2022-11-11 22:31 UTC, merged

2022-11-11 22:31 UTC, bzm3r commented
@nerdachse merged :)