Fix broken rendering of tilemaps with padding in atlas mode
StarArawn/bevy_ecs_tilemap pull request #363
Opened 2022-11-29 22:13 UTC by rparrett

`var columns` was mistakenly adding rather than subtracting one side of the spacing, potentially causing the wrong tiles to be displayed. This bug was not visible in the spacing example.

`sprite_sheet_x` and `sprite_sheet_y` were not accounting for the what bevy calls the "offset" -- the spacing in the left gutter of the texture.

Before:
`cargo run --example spacing --features=atlas`
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/200550/204659490-4e0f556d-0a89-4567-afe9-dd2b10d63430.png">

After
`cargo run --example spacing --features=atlas`
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/200550/204659610-5cf91673-7a7b-4d4d-a1e9-3db126ec7bc3.png">

Note: the spacing example is intentionally displaying an incorrectly configured tilemap in blue.

2022-12-10 22:38 UTC, bzm3r commented
@rparrett thanks for your patience on this; I've asked StarArawn to review, but he is currently super busy, so it may take a while!

But this does look good to me!

2022-12-10 22:40 UTC, bzm3r requested changes

2022-12-10 22:40 UTC, bzm3r commented on src/render/shaders/tilemap_vertex.wgsl
> +    var columns: u32 = u32((tilemap_data.texture_size.x - tilemap_data.spacing.x) / (tilemap_data.tile_size.x + tilemap_data.spacing.x));
I think this makes sense to me? But I'm wondering if we can add some more comments here, similar to what the PR text includes, for future readers?

2022-12-11 15:58 UTC, StarArawn approved these changes

2022-12-11 16:35 UTC, StarArawn approved these changes

2022-12-11 16:36 UTC, merged