Add `physical_tile_size` field to determine how large each tile is rendered in-world
StarArawn/bevy_ecs_tilemap pull request #376
Opened 2022-12-29 06:20 UTC by SirHall

As `bevy_ecs_tilemap` stands now, each tile's size in-world is tied to the pixel-size of the tile in the source atlas.
If I however want my tiles to be of unit size or any particular scale that I require, this is not currently possible.
With this pull request, a user can now set `physical_tile_size` to determine how large a tile should be rendered in-world.

This should also close #337.

2023-01-10 00:17 UTC, bzm3r requested changes
I am not sure about the name `physical_tile_size`. `physical` is a bit of an overloaded term.

I think `TilemapTileSize` should behave exactly like the new `TilemapPhysicalTileSize`.

Instead, there should be a separate type called `SourceTileSize`, which specifies how large a tile is in the source texture. It should not be a field on `TilemapBundle`, instead the variants of `TilemapTexture` should be structs which have a field `tile_size: SourceTileSize`

`TilemapTileSize` should be an option on `TilemapBundle`. Currently we have:

https://github.com/StarArawn/bevy_ecs_tilemap/blob/cac7598fbcd518f9f6c6587add280be30f66d484/src/lib.rs#L103

Instead this should be `pub tile_size: Option<TilemapTileSize>`

If the user wants to specify an explicit `TilemapTileSize`, they can do so by providing `Some(TilemapTileSize { ... })`, otherwise it should be initialized based on the `SourceTileSize` provided for the `TilemapTexture` 

The shaders should get two pieces of info: the `SourceTileSize`, and the `TilemapTileSize`

Let me know if this makes sense to you? I think implementing this shouldn't be too hard based on what you've written so far; it will require some variable renaming and some work on `TilemapTexture`, but will be a clearer solution overall?

@StarArawn @rparrett Let me know if the above review suggestion makes sense to you guys too.

2023-01-10 07:15 UTC, SirHall commented on examples/bench.rs
> +    println!("{:#?}", grid_size);
I thought I checked for things like that!
Sorry will remove.

2023-01-10 07:20 UTC, SirHall commented
Yeah that's fine, to me 'physical' meant how large it would *'physically'* appear in the game-world.
I'm now thinking it may actually be even clearer to have one be `TilemapSourceTileSize` and the in-world one be `TilemapPhysicalTileSize` to clearly separate both - though I'm fine with any reasonable naming scheme.
I don't have time immediately to go over it so I'll probably have to do it the day after tomorrow for me.

2023-01-13 05:07 UTC, bzm3r commented
I would prefer `TilemapSourceTileSize` and `TilemapTileSize`. Or `TextureTileSize` and `TilemapTileSize`. 

I am just not a fan of "physical" because it comes up a lot in gpu stuff with fairly different meanings. In programming more generally, the term "physical" is often contrasted with "logical"; if there is a `TilemapPhysicalTileSize`, is there a `TilemapLogicalTileSize`?

2023-01-13 13:46 UTC, rparrett commented
Agree that `TilemapPhysicalTileSize` strikes me as referring to physical pixels on a screen.

> Instead this should be `pub tile_size: Option<TilemapTileSize>`

I don't think bevy will let us do that.

2023-01-21 08:05 UTC, SirHall commented
I do think the comparison to GPU architecture is being a little pedantic - but I'm fine with any reasonable option, do let me know with the two names once it's settled.

2023-11-21 12:39 UTC, juzi5201314 commented
Useful feature, can we still hope to get it? Or can such a function be achieved on existing code?

2023-11-22 00:42 UTC, SirHall commented
> Useful feature, can we still hope to get it? Or can such a function be achieved on existing code?

I have been quite busy for a while recently and only a few days thought of updating this PR to finally get it merged in, ideally I can get this merged in shortly.

2023-12-20 04:58 UTC, MeoMix commented
just FYI I am working on addressing the PRs concerns in my own branch, should have it done tmmw

2024-11-01 06:15 UTC, SirHall commented
Sorry for the long hiatus, this has been reworked, `physical` renamed to `in_world` (as I feel this causes the least confusion) and should be good to merge.

2024-11-11 09:27 UTC, SirHall commented
I don't know if @bzm3r is still active, could we have a new reviewer for this PR?

2024-12-12 08:17 UTC, closed without merging

2024-12-26 04:59 UTC, SirHall commented
> @SirHall I'm no longer active, sorry! I also apologize if I was too pedantic early on regarding how things ought to be named, and thus delayed getting this merged sooner.

All good, hope you're doing well!