make it clear bevy 0.14 is supported
StarArawn/bevy_ecs_tilemap pull request #543
Opened 2024-07-22 23:33 UTC by ChristopherBiscardi

2024-07-22 23:34 UTC, StarArawn requested changes

2024-07-22 23:34 UTC, StarArawn commented on README.md
>  |0.12|0.12|
lets add:
`|0.13| - |`
just so its clear no release was made.

2024-07-23 00:28 UTC, ChristopherBiscardi commented on README.md
>  |0.12|0.12|
done

2024-07-23 01:26 UTC, StarArawn approved these changes

2024-07-23 01:26 UTC, merged